# Site wide configuration

title: "Maya Siva | Portfolio"
name: "Maya Siva"
description: "Financial Mathematics Student at Cardiff University"

# Bio (This shows up under your picture on the left sidebar)
bio: "First-year Financial Mathematics student at Cardiff University with an interest in corporate finance, risk management, and quantitative data analysis."

# Social Links (Put your handles here, or leave blank to hide them)
email: "mayasiva06@gmail.com"
linkedin: "Maya Siva"
github: "mayasiva06"

url: "https://mayasiva06.github.io"
repository: "mayasiva06/mayasiva06.github.io"
